In [1]:
# import required libs
import pickle
import numpy as np
import tensorflow as tf
from matplotlib import pyplot as plt
from tensorflow.keras import Sequential
from tensorflow.keras import layers

In [2]:
# load previously saved preprocessed data
X = pickle.load(open('X.pkl', 'rb')) # rb = read in binary
y = pickle.load(open('y.pkl', 'rb'))

In [3]:
len(X)

25000

In [4]:
X

array([[[[ 24,  26,  27],
         [ 24,  26,  27],
         [ 25,  27,  28],
         ...,
         [ 55,  62,  61],
         [ 54,  62,  64],
         [ 54,  61,  64]],

        [[ 24,  26,  27],
         [ 24,  26,  27],
         [ 25,  27,  28],
         ...,
         [ 52,  64,  65],
         [ 52,  63,  64],
         [ 53,  61,  59]],

        [[ 25,  27,  28],
         [ 25,  27,  28],
         [ 25,  27,  28],
         ...,
         [ 59,  69,  63],
         [ 60,  65,  55],
         [ 54,  60,  55]],

        ...,

        [[ 28,  18,  30],
         [ 31,  21,  34],
         [ 31,  19,  37],
         ...,
         [ 33,  19,  37],
         [ 33,  19,  37],
         [ 33,  20,  36]],

        [[ 27,  20,  25],
         [ 29,  18,  34],
         [ 29,  19,  32],
         ...,
         [ 28,  17,  33],
         [ 32,  22,  34],
         [ 32,  22,  35]],

        [[ 27,  20,  25],
         [ 29,  18,  34],
         [ 29,  19,  32],
         ...,
         [ 28,  17,  33],
        

In [5]:
y

array([1, 1, 1, ..., 1, 1, 1])

In [6]:
# Normalization is a scaling technique in which values are shifted and rescaled 
# so that they end up ranging between 0 and 1. It is also known as Min-Max scaling
X = X/255 # feature scaling 

In [8]:
X

array([[[[0.38823529, 0.37254902, 0.56862745],
         [0.39215686, 0.37647059, 0.56862745],
         [0.4       , 0.38431373, 0.57254902],
         ...,
         [0.38823529, 0.42352941, 0.67058824],
         [0.38431373, 0.41960784, 0.66666667],
         [0.38039216, 0.41568627, 0.6627451 ]],

        [[0.37647059, 0.36470588, 0.57647059],
         [0.38039216, 0.37254902, 0.57647059],
         [0.38431373, 0.37647059, 0.58039216],
         ...,
         [0.37254902, 0.41568627, 0.65882353],
         [0.37254902, 0.41568627, 0.65882353],
         [0.37254902, 0.41568627, 0.65882353]],

        [[0.35294118, 0.36078431, 0.58431373],
         [0.35686275, 0.36470588, 0.59215686],
         [0.36470588, 0.36862745, 0.59215686],
         ...,
         [0.36078431, 0.41176471, 0.6627451 ],
         [0.36862745, 0.41568627, 0.66666667],
         [0.36862745, 0.41568627, 0.66666667]],

        ...,

        [[0.44313725, 0.48235294, 0.57647059],
         [0.45098039, 0.49019608, 0.58431373]

In [7]:
X.shape

(25000, 96, 96, 3)

In [8]:
# now design CNN Model
model = tf.keras.models.Sequential([# Convolutional layer 1
                                    tf.keras.layers.Conv2D(64, (3, 3), activation='relu', input_shape=(96, 96, 3)),
                                    tf.keras.layers.MaxPooling2D(2, 2),

                                    # Convolutional layer 2
                                    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
                                    tf.keras.layers.MaxPooling2D(2, 2),

                                    # Flatten layer - Output of convolution
                                    tf.keras.layers.Flatten(),
                
                                    # Hidden layer
                                    tf.keras.layers.Dense(128, activation=tf.nn.relu),

                                    # Output layer
                                    tf.keras.layers.Dense(2, activation=tf.nn.softmax)])

In [9]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 94, 94, 64)        1792      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 47, 47, 64)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 45, 45, 64)        36928     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 22, 22, 64)       0         
 2D)                                                             
                                                                 
 flatten (Flatten)           (None, 30976)             0         
                                                                 
 dense (Dense)               (None, 128)               3

In [11]:
history = model.fit(X, y, epochs=5)

Epoch 1/5
782/782 [==============================] - 179s 203ms/step - loss: 0.6433 - accuracy: 0.6303
Epoch 2/5
782/782 [==============================] - 157s 201ms/step - loss: 0.5092 - accuracy: 0.7504
Epoch 3/5
782/782 [==============================] - 156s 199ms/step - loss: 0.4030 - accuracy: 0.8160
Epoch 4/5
782/782 [==============================] - 156s 200ms/step - loss: 0.2812 - accuracy: 0.8799
Epoch 5/5
782/782 [==============================] - 156s 200ms/step - loss: 0.1409 - accuracy: 0.9444


In [12]:
# Model Evaluation
scores = model.evaluate(X, y)

782/782 [==============================] - 80s 79ms/step - loss: 0.0539 - accuracy: 0.9891


In [13]:
model.save("model.h5")